### ISSUE TITLE
How can add participant as listener

### ISSUE THREAD

**Issue by asadumair** [voxeet/voxeet-cordova-conferencekit#81] opened 2022-12-29 14:10 UTC
in documentation there is listen() method to add participitant as listner but this is not present in sdk only join is there so how can i join as a listner?

**Comment by FabienLavocat** [comment] 2022-12-30 00:48
I am closing this issue as it is a duplicate of https://github.com/dolbyio-samples/comms-sdk-react-native-getting-started/issues/9

**Closed as not planned by FabienLavocat** 2022-12-30 00:48 UTC
Labels: duplicate
